version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: dbmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: c7c0d4c335ddef9c6094b655c39805e4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: c7c0d4c335ddef9c6094b655c39805e4
      ME_CONFIG_BASICAUTH_USERNAME: victor
      ME_CONFIG_BASICAUTH_PASSWORD: c7c0d4c335ddef9c6094b655c39805e4
      ME_CONFIG_MONGODB_PORT: 27017

  web:
    build: .
    depends_on: 
        - mongo
        - mongo-express
    volumes:
        - .:/SOLDADOX