version: '3'
services:
    db:
        image: postgres:12-alpine
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: default_db
        ports:
            - 54320:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    adminer:
        image: adminer
        restart: always
        depends_on: 
            - db
        ports:
          - 8080:8080

    web:
        build: .
        depends_on: 
            - db
            - adminer
        volumes:
            - .:/SOLDADOX
        ports:
        - "5001:5001"

volumes:
    postgres_data: